INSERT INTO TBL_USER(ID,USER_NAME,PASSWORD,EMAIL,ROLE) VALUES(
1001,'PrinseeJii','admin@123','prinsee@gmail.com','ADMIN'
);
INSERT INTO TBL_USER(ID,USER_NAME,PASSWORD,EMAIL,ROLE) VALUES(
1002,'Vaibhav','admin@123','vaibhav@gmail.com','ADMIN'
);
INSERT INTO TBL_USER(ID,USER_NAME,PASSWORD,EMAIL,ROLE) VALUES(
1003,'Anshul','admin@123','anshul@gmail.com','ADMIN'
);
INSERT INTO TBL_USER(ID,USER_NAME,PASSWORD,EMAIL,ROLE) VALUES(
1004,'Maa','admin@123','maa@gmail.com','ADMIN'
);
INSERT INTO TBL_USER(ID,USER_NAME,PASSWORD,EMAIL,ROLE) VALUES(
1005,'Paa','admin@123','paa@gmail.com','ADMIN'
);